[package]
name = "featomic"
version = "0.6.7"
authors = ["Guillaume Fraux <guillaume.fraux@epfl.ch>"]
edition = "2021"
rust-version = "1.88"

description = "Library to compute representations for atomistic machine learning"
# readme = "TODO"
documentation = "https://metatensor.github.io/featomic/"
repository = "https://github.com/metatensor/featomic"
license = "BSD-3-Clause"

[lib]
bench = false

[features]
default = []
# Include the code for the featomic C API
c-api = ["time-graph/table", "time-graph/json", "log/std"]
# use a static library for metatensor instead of a shared one
metatensor-static = ["metatensor/static"]

[package.metadata."docs.rs"]
all-features = true

[dependencies]
metatensor = { version = "0.5", features = ["rayon"]}

ndarray = {version = "0.17", features = ["rayon", "serde", "approx"]}
num-traits = "0.2"
rayon = "1.5"
log = "0.4"
indexmap = "2"
thread_local = "1.1"
time-graph = "0.3"

ouroboros = "0.18"

serde = { version = "1", features = ["derive"] }
serde_json = "1"
schemars = "1"

chemfiles = { version = "0.10", optional = true, features = ["build-from-sources"]}

approx = "0.5"

[build-dependencies]
cbindgen = { version = "0.29", default-features = false }
fs_extra = "1"
metatensor = { version = "0.5" }

[dev-dependencies]
criterion = "0.5"
which = "8"
glob = "0.3"
flate2 = "1"
time-graph = {version = "0.3.0", features = ["table", "json"]}

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin)'] }

[[bench]]
name = "spherical-harmonics"
harness = false

[[bench]]
name = "lode-spherical-expansion"
harness = false
required-features = ["chemfiles"]

[[bench]]
name = "soap-spherical-expansion"
harness = false
required-features = ["chemfiles"]

[[bench]]
name = "soap-power-spectrum"
harness = false
required-features = ["chemfiles"]

[[example]]
name = "compute-soap"
required-features = ["chemfiles"]

[[example]]
name = "profiling"
required-features = ["chemfiles"]
